server:
  port: 5000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri:
              lb://user-service
            predicates:
              - PATH=/auth/**, /users/**, /api/users/**, /
          - id: task-service
            uri:
              lb://task-service
            predicates:
              - PATH=/api/tasks/**, /tasks/**
          - id: submission-service
            uri:
              lb://submission-service
            predicates:
              - PATH=/api/submissions/**, /submissions/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/